### ISSUE TITLE
the xlsx isn't showing app ver

### ISSUE THREAD

**Issue by mtnjustme** [n1ghty/pkg_tools#1]
title.
also not showing system ver but i dont know if it's supposed though (saw the title in xlsxlist.py).
ty for your work man.

**Comment by mtnjustme** [comment]
i've watched that i can add the column in the command line and i did.
however, 1.7 appears as 1700000
amazing work however :).
'{}.{}'.format(pkg_info['SYSTEM_VER'][0], pkg_info['SYSTEM_VER'][1:3])

doesn't seem to do the job.

**Comment by mtnjustme** [comment]
i've fixed the code for u :
pkg_info['SYSTEM_VER'] = '{}.{}'.format(pkg_info['SYSTEM_VER'][0], pkg_info['SYSTEM_VER'][1:3])

instead of :
pkg_info['SYS_VER'] = '{}.{}'.format(pkg_info['SYSTEM_VER'][0], pkg_info['SYSTEM_VER'][1:3])

**Comment by n1ghty** [comment]
It's not an error. SYSTEM_VER is the unmodified info from Param.sfo and SYS_VER is the formatted one. See help text :)

Also, the VER version field had a bug in V1.1.0. This was fixed with V1.1.1

**Comment by mtnjustme** [comment]
no man the version isn't showing in 1.1.1...
i tried it.
when changing the line i told u about it's working.
your code has a bug probably.

**Comment by n1ghty** [comment]
Your change would  overwrite the raw param.sfo data, which is not what I want to do.

I can't replicate your error.
`python pkg_list.py k: -c TITLE SYSTEM_VER SYS_VER APP_VER VERSION VER`

TITLE | SYSTEM_VER | SYS_VER | APP_VER | VERSION | VER
-- | -- | -- | -- | -- | --
P.T. | 1500000 | 1.50 | 01.00 | 01.00 | 01.00

**Comment by mtnjustme** [comment]
oh i see what you mean... makes sense.
so system_ver is the param's info and you don't want to change it because it'll overwrite the param.sfo.
i see so it's my bad then.

**Comment by mtnjustme** [comment]
i mean the original info dumped by the param.sfo...
